# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a5aabdad694c5738a2b590f96cc593f9eb7ddafb085384f0fc06c0699804f7593ac2c2783becadd4bf709f16643a4df18cc9f4b2135bb8dae27723fcc606ff

test:
  secret_key_base: ea906f2884f6b3ea3539668d89f900d3b527cacc6fed6f66a2b41b4442e5a0025ff0410033812f5d655a643a9844e869d26abcb75d1f52144c4ef66254568b98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
